# Generated by Django 4.1.2 on 2022-10-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='curriculo',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='curso',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='github',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='google_scholar',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='linkedin',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='orcid',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='research_gate',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='tipo',
            field=models.CharField(choices=[(1, 'Autor'), (2, 'Coautor'), (3, 'Discentes')], default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='universidade',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
    ]
