# Generated by Django 3.2.16 on 2022-11-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pessoa_curriculo_alter_pessoa_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='tipo',
            field=models.CharField(choices=[('1', 'Autor'), ('2', 'Orientador'), ('3', 'Coorientador')], max_length=30),
        ),
    ]
