# Generated by Django 3.2.16 on 2022-11-13 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20221113_1247'),
        ('monografia', '0003_alter_monografia_data_alter_monografia_palavrachave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monografia',
            name='autor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='autor', to='core.pessoa'),
        ),
        migrations.AlterField(
            model_name='monografia',
            name='coorientador',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='coorientador', to='core.pessoa'),
        ),
        migrations.AlterField(
            model_name='monografia',
            name='orientador',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='orientador', to='core.pessoa'),
        ),
    ]
