# Generated by Django 4.1.2 on 2022-10-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=200)),
                ('titulo', models.CharField(default='', max_length=30)),
                ('autor', models.CharField(default='', max_length=31)),
                ('orientador', models.CharField(default='', max_length=33)),
                ('coorientador', models.CharField(default='', max_length=35)),
                ('data', models.CharField(default='', max_length=30)),
                ('resumo', models.CharField(default='', max_length=30)),
                ('palavrachave', models.CharField(default='', max_length=30, verbose_name='Palavra-chave')),
                ('universidade', models.CharField(default='', max_length=30)),
                ('curso', models.CharField(default='', max_length=50)),
                ('link', models.CharField(default='', max_length=200, verbose_name='Link para PDF')),
            ],
        ),
    ]
