# Generated by Django 4.1.2 on 2022-10-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pessoa_curriculo_pessoa_curso_pessoa_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='curriculo',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(default='', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='github',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='google_scholar',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='linkedin',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='orcid',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='research_gate',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
